// <auto-generated/>

namespace Domain.Entities.FrontEnd
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    public class Google
    {
        public string issued_to { get; set; }

        public string email { get; set; }

        public string audience { get; set; }

        public string user_id { get; set; }

        public string scope { get; set; }

        public int expires_in { get; set; }

        public string access_type { get; set; }

        public string error { get; set; }
    }
}
