// <auto-generated/>

namespace Domain.Entities.FrontEnd
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    public class LinkedInUser
    {
        public string id { get; set; }

        public string image { get; set; }

        public string error { get; set; }
    }
}
