// <auto-generated/>

namespace Domain.Entities.FrontEnd
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    public class ShrareUrl
    {
        public string ideaId { get; set; }

        public string name { get; set; }

        public string link { get; set; }

        public string picture { get; set; }

        public string caption { get; set; }

        public string description { get; set; }

        public string descriptionFB { get; set; }

        public string descriptionTW { get; set; }
    }
}
