//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Extend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Extend.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrega tu comentario.
        /// </summary>
        internal static string ADDYOURCOMMENT {
            get {
                return ResourceManager.GetString("ADDYOURCOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo puedes escribir 250 caractéres.
        /// </summary>
        internal static string ALONECAN {
            get {
                return ResourceManager.GetString("ALONECAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione los filtros que desea aplicar.
        /// </summary>
        internal static string APPLY_FILTERS {
            get {
                return ResourceManager.GetString("APPLY_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner no disponible.
        /// </summary>
        internal static string BANNERNO {
            get {
                return ResourceManager.GetString("BANNERNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear idea.
        /// </summary>
        internal static string BLOCK_IDEA {
            get {
                return ResourceManager.GetString("BLOCK_IDEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear usuario.
        /// </summary>
        internal static string BLOCK_USER {
            get {
                return ResourceManager.GetString("BLOCK_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniendo fuerzas podremos construir la ciudad que soñamos.
        /// </summary>
        internal static string BYJOINN {
            get {
                return ResourceManager.GetString("BYJOINN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tambíen, puedes escribirnos a.
        /// </summary>
        internal static string CANALSO {
            get {
                return ResourceManager.GetString("CANALSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoge tu respuesta.
        /// </summary>
        internal static string CHOOSEANSWER {
            get {
                return ResourceManager.GetString("CHOOSEANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige la idea que más te guste para nuestra ciudad..
        /// </summary>
        internal static string CHOOSECITY {
            get {
                return ResourceManager.GetString("CHOOSECITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participación ciudadana.
        /// </summary>
        internal static string CITIZENPARTI {
            get {
                return ResourceManager.GetString("CITIZENPARTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ciudadanos están co-creando en CITIES FOR LIFE.
        /// </summary>
        internal static string CITIZENSCO {
            get {
                return ResourceManager.GetString("CITIZENSCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reto ciudad.
        /// </summary>
        internal static string CITYCHA {
            get {
                return ResourceManager.GetString("CITYCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuando tú hablas, la ciudad escucha..
        /// </summary>
        internal static string CITYHEARD {
            get {
                return ResourceManager.GetString("CITYHEARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finalizado-espanol.
        /// </summary>
        internal static string CLASSFINALIZADO {
            get {
                return ResourceManager.GetString("CLASSFINALIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finalizado-interna-espanol.
        /// </summary>
        internal static string CLASSFINALIZADOINTERNA {
            get {
                return ResourceManager.GetString("CLASSFINALIZADOINTERNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to perfil-clasificacion-espanol.
        /// </summary>
        internal static string CLASSPERFILES {
            get {
                return ResourceManager.GetString("CLASSPERFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tooltip-moneda-espanol.
        /// </summary>
        internal static string CLASSTOOLTIPMONEDA {
            get {
                return ResourceManager.GetString("CLASSTOOLTIPMONEDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tooltip-moneda-profile-espanol.
        /// </summary>
        internal static string CLASSTOOLTIPMONEDAPROFILE {
            get {
                return ResourceManager.GetString("CLASSTOOLTIPMONEDAPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que desea eliminar los registros de la auditoria?.
        /// </summary>
        internal static string CLEAN_AUDIT {
            get {
                return ResourceManager.GetString("CLEAN_AUDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina toda la información de la auditoria de la aplicación..
        /// </summary>
        internal static string CLEAN_AUDIT_MESSAGE {
            get {
                return ResourceManager.GetString("CLEAN_AUDIT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que desea eliminar los registros del log de la aplicación?.
        /// </summary>
        internal static string CLEAN_LOG {
            get {
                return ResourceManager.GetString("CLEAN_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina toda la información del log de errores.
        /// </summary>
        internal static string CLEAN_LOG_MESSAGES {
            get {
                return ResourceManager.GetString("CLEAN_LOG_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudadanos comprometidos.
        /// </summary>
        internal static string COMPROMCITIZENS {
            get {
                return ResourceManager.GetString("COMPROMCITIZENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu contraseña ha sido cambiada..
        /// </summary>
        internal static string CONFIRMPASSWORD {
            get {
                return ResourceManager.GetString("CONFIRMPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        internal static string CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATROCINADORES.
        /// </summary>
        internal static string CONTRIBUTOR {
            get {
                return ResourceManager.GetString("CONTRIBUTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Noticia.
        /// </summary>
        internal static string CREATENEWS {
            get {
                return ResourceManager.GetString("CREATENEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles actuales.
        /// </summary>
        internal static string CURRENT_ROLE {
            get {
                return ResourceManager.GetString("CURRENT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Política de protección de datos.
        /// </summary>
        internal static string DATAPROTECTION {
            get {
                return ResourceManager.GetString("DATAPROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to días &lt;br&gt; restantes.
        /// </summary>
        internal static string DAYREMAINING {
            get {
                return ResourceManager.GetString("DAYREMAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to día(s) de acabarse.
        /// </summary>
        internal static string DAYS {
            get {
                return ResourceManager.GetString("DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to días restantes.
        /// </summary>
        internal static string DAYSREMA {
            get {
                return ResourceManager.GetString("DAYSREMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de borrar tu comentario?.
        /// </summary>
        internal static string DELETE_COMMENT_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_COMMENT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Borrar tu Comentario?.
        /// </summary>
        internal static string DELETE_COMMENT_TITLE {
            get {
                return ResourceManager.GetString("DELETE_COMMENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de borrar tu idea?.
        /// </summary>
        internal static string DELETE_IDEA_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_IDEA_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Borrar tu Idea?.
        /// </summary>
        internal static string DELETE_IDEA_TITLE {
            get {
                return ResourceManager.GetString("DELETE_IDEA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que desea eliminar el registro?.
        /// </summary>
        internal static string DELETE_ITEM {
            get {
                return ResourceManager.GetString("DELETE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de borrar esta noticia?.
        /// </summary>
        internal static string DELETE_NEWS_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_NEWS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Borrar Noticia?.
        /// </summary>
        internal static string DELETE_NEWS_TITLE {
            get {
                return ResourceManager.GetString("DELETE_NEWS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si no deseas seguir recibiendo estos correos, escríbenos a info@citiesfor.life con la palabra &quot;desactivar correo&quot;.
        /// </summary>
        internal static string DISABLEMAIL {
            get {
                return ResourceManager.GetString("DISABLEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descubre cuantos likes y comentarios ha generado tu participación..
        /// </summary>
        internal static string DISCOVERHOW {
            get {
                return ResourceManager.GetString("DISCOVERHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Sabes lo que logras cuando te empoderas de tu territorio?&lt;br&gt;&lt;span&gt; Estos proyectos te demuestran que las ciudades las crean sus habitantes.&lt;/span&gt;.
        /// </summary>
        internal static string DOYOUKNOW {
            get {
                return ResourceManager.GetString("DOYOUKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ecosistema CITIES FOR LIFE espera tu aporte..
        /// </summary>
        internal static string ECOCITIESFORLIFE {
            get {
                return ResourceManager.GetString("ECOCITIESFORLIFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edita tu idea.
        /// </summary>
        internal static string EDITIDEA {
            get {
                return ResourceManager.GetString("EDITIDEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviarme un correo cuando una de mis idea sea bloqueada.
        /// </summary>
        internal static string EMAILME {
            get {
                return ResourceManager.GetString("EMAILME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu correo electrónico:.
        /// </summary>
        internal static string ENTEREMAIL {
            get {
                return ResourceManager.GetString("ENTEREMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa un mensaje.
        /// </summary>
        internal static string ENTERMESS {
            get {
                return ResourceManager.GetString("ENTERMESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estás bloqueado..
        /// </summary>
        internal static string ERRORBLOCKED {
            get {
                return ResourceManager.GetString("ERRORBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa un correo válido.
        /// </summary>
        internal static string ERROREMAIL {
            get {
                return ResourceManager.GetString("ERROREMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu idea debe tener máximo.
        /// </summary>
        internal static string ERRORMAXIDEA {
            get {
                return ResourceManager.GetString("ERRORMAXIDEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo no es válido.
        /// </summary>
        internal static string ERRORMESSAGESEMAIL {
            get {
                return ResourceManager.GetString("ERRORMESSAGESEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo no tiene una cuenta asociada..
        /// </summary>
        internal static string ERRORMESSAGESEMAIL2 {
            get {
                return ResourceManager.GetString("ERRORMESSAGESEMAIL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu idea debe tener mínimo 20 caracteres..
        /// </summary>
        internal static string ERRORMIN20 {
            get {
                return ResourceManager.GetString("ERRORMIN20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa un número celular válido.
        /// </summary>
        internal static string ERRORMOVIL {
            get {
                return ResourceManager.GetString("ERRORMOVIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número celular invalido.
        /// </summary>
        internal static string ERRORMOVILINVALIDO {
            get {
                return ResourceManager.GetString("ERRORMOVILINVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa una contraseña.
        /// </summary>
        internal static string ERRORPASSWORD {
            get {
                return ResourceManager.GetString("ERRORPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo o la contraseña es incorrecta. ¡Intenta de nuevo!.
        /// </summary>
        internal static string ERRORPASSWORDINVALIDO {
            get {
                return ResourceManager.GetString("ERRORPASSWORDINVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aún no cambiamos tu contraseña. ¡Vuelve a intentarlo!.
        /// </summary>
        internal static string ERRORPASSWORDNOSAVE {
            get {
                return ResourceManager.GetString("ERRORPASSWORDNOSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu información no ha sido actualizada, puede que la dirección ingresada no sea válida. ¡Ingresa la dirección completa!.
        /// </summary>
        internal static string ERRORREDESSOCIALES {
            get {
                return ResourceManager.GetString("ERRORREDESSOCIALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecciona una ubicación en el mapa..
        /// </summary>
        internal static string ERRORSELECTMAP {
            get {
                return ResourceManager.GetString("ERRORSELECTMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Información incorrecta!.
        /// </summary>
        internal static string ERRORTITULO {
            get {
                return ResourceManager.GetString("ERRORTITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa un vídeo válido..
        /// </summary>
        internal static string ERRORVIDEOINVALIDO {
            get {
                return ResourceManager.GetString("ERRORVIDEOINVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu voto no ha sido guardado, ¡Ya habías votado en esta pregunta!.
        /// </summary>
        internal static string ERRORVOTO {
            get {
                return ResourceManager.GetString("ERRORVOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu voto no ha sido guardado. ¡Intenta de nuevo!.
        /// </summary>
        internal static string ERRORVOTOSAVE {
            get {
                return ResourceManager.GetString("ERRORVOTOSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESA QUE SE EDIFICA CON EL APORTE DE TODOS..
        /// </summary>
        internal static string ESATHAT {
            get {
                return ResourceManager.GetString("ESATHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporta la información de la auditoria de la aplicación a formato excel..
        /// </summary>
        internal static string EXPORT_AUDIT {
            get {
                return ResourceManager.GetString("EXPORT_AUDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporta la información del log de errores a formato excel..
        /// </summary>
        internal static string EXPORT_LOG {
            get {
                return ResourceManager.GetString("EXPORT_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo verificar la información.
        /// </summary>
        internal static string FAILED_INFORMATION {
            get {
                return ResourceManager.GetString("FAILED_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuentra las mejores ideas de la pregunta en la que estás navegando.
        /// </summary>
        internal static string FINDBEST {
            get {
                return ResourceManager.GetString("FINDBEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Entérate!.
        /// </summary>
        internal static string FINDOUT {
            get {
                return ResourceManager.GetString("FINDOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por el nombre.
        /// </summary>
        internal static string FIND_BY_NAME {
            get {
                return ResourceManager.GetString("FIND_BY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por palabra o frase.
        /// </summary>
        internal static string FIND_BY_TEXT {
            get {
                return ResourceManager.GetString("FIND_BY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las buenas  ideas nos llevan a ese futuro donde queremos estar..
        /// </summary>
        internal static string FUTURE {
            get {
                return ResourceManager.GetString("FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genero.
        /// </summary>
        internal static string GENDER {
            get {
                return ResourceManager.GetString("GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busqueda general.
        /// </summary>
        internal static string GENERAL_SEARCH {
            get {
                return ResourceManager.GetString("GENERAL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !CONÓCENOS!.
        /// </summary>
        internal static string GETTOKNOW {
            get {
                return ResourceManager.GetString("GETTOKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;¿Quieres saber más de nuestras experiencias?&lt;/span&gt;&lt;br&gt;Aquí te contamos algunas historias de ciudades para la vida..
        /// </summary>
        internal static string HOMESECTIONS7 {
            get {
                return ResourceManager.GetString("HOMESECTIONS7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Tienes una propuesta que puede transformar ciudades para la vida?&lt;br&gt;&lt;span&gt;Aquí puedes compartirlas con ciudadanos de todo el mundo.&lt;/span&gt;.
        /// </summary>
        internal static string HOME_SECCION4 {
            get {
                return ResourceManager.GetString("HOME_SECCION4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya se.
        /// </summary>
        internal static string IKNOW {
            get {
                return ResourceManager.GetString("IKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen Máximo 5MB.
        /// </summary>
        internal static string IMAGEMX {
            get {
                return ResourceManager.GetString("IMAGEMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/img-slide-3-espanol.png.
        /// </summary>
        internal static string IMGHOMESLIDE1 {
            get {
                return ResourceManager.GetString("IMGHOMESLIDE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de la información de la auditoria de la aplicación..
        /// </summary>
        internal static string INFORMATION_AUDIT {
            get {
                return ResourceManager.GetString("INFORMATION_AUDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento del log de errores de la aplicación..
        /// </summary>
        internal static string INFORMATION_LOG {
            get {
                return ResourceManager.GetString("INFORMATION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una de las secciones para modificar la información..
        /// </summary>
        internal static string INFORMATION_SECTION {
            get {
                return ResourceManager.GetString("INFORMATION_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este ecosistema de co-creación global está en continuo desarrollo. Si tienes sugerencias y recomendaciones, envíalas a &lt;a href=&quot;mailto:info@citiesfor.life&quot;&gt;info@citiesfor.life&lt;/a&gt;. Juntos integraremos el conocimiento y superaremos los retos de nuestras ciudades..
        /// </summary>
        internal static string INICIOENBETA {
            get {
                return ResourceManager.GetString("INICIOENBETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este año el Encuentro Global tendrá lugar en París, donde estamos ansiosos de presentar nuestros mejores casos de éxito e ideas de como enfrentar retos urbanos. &lt;br /&gt;&lt;br /&gt;
        ///Empecemos por compartir conocimiento y fortalecer la colaboración entre nuestras ciudades. Emprender este camino por sí sólo puede resultar abrumador. Nosotros creemos que es más emocionante, divertido y exitoso cuando co-creamos, comunicamos y encendemos el motor del cambio mancomunadamente..
        /// </summary>
        internal static string INNOVATION {
            get {
                return ResourceManager.GetString("INNOVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspírate, crea y transforma aquí:.
        /// </summary>
        internal static string INSPIRED {
            get {
                return ResourceManager.GetString("INSPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institucion que Implementa.
        /// </summary>
        internal static string INSTIMPLEM {
            get {
                return ResourceManager.GetString("INSTIMPLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intitucion origen.
        /// </summary>
        internal static string INSTSOURCE {
            get {
                return ResourceManager.GetString("INSTSOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sube un video.
        /// </summary>
        internal static string ITGOES {
            get {
                return ResourceManager.GetString("ITGOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sube una imagen.
        /// </summary>
        internal static string ITGOESIMA {
            get {
                return ResourceManager.GetString("ITGOESIMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participa en esta iniciativa ciudadana.
        /// </summary>
        internal static string JOININITIATIVE {
            get {
                return ResourceManager.GetString("JOININITIATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimas actividades.
        /// </summary>
        internal static string LAST_ACTIVITY {
            get {
                return ResourceManager.GetString("LAST_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIDERA.
        /// </summary>
        internal static string LEADING {
            get {
                return ResourceManager.GetString("LEADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar archivos.
        /// </summary>
        internal static string LOAD_FILES {
            get {
                return ResourceManager.GetString("LOAD_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                            &lt;strong&gt;PROTECCIÓN  DE DATOS Y POLÍTICA DE PRIVACIDAD DATOS PERSONALES&lt;/strong&gt;
        ///                        &lt;/p&gt;
        ///                        &lt;p&gt;
        ///                            Para la participación en la plataforma, &lt;strong&gt;RUTA N&lt;/strong&gt;, actuando como responsable de los datos, recopila información personal, como: Nombre, Apellido, email, usuario y contraseña.
        ///                        &lt;/p&gt;
        ///                        &lt;p&gt;
        ///                            &lt;strong&gt;RUTA N&lt;/strong&gt; recopila [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LONGTEXT {
            get {
                return ResourceManager.GetString("LONGTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo se enviara a.
        /// </summary>
        internal static string MAILTO {
            get {
                return ResourceManager.GetString("MAILTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen principal para tu noticia.
        /// </summary>
        internal static string MAINIMAGE {
            get {
                return ResourceManager.GetString("MAINIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden manual.
        /// </summary>
        internal static string MANUAL_ORDER {
            get {
                return ResourceManager.GetString("MANUAL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisa tu correo.
        /// </summary>
        internal static string MESSAGESSSENDEMAIL1 {
            get {
                return ResourceManager.GetString("MESSAGESSSENDEMAIL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviamos un mensaje a tu correo electrónico para que cambies tu contraseña..
        /// </summary>
        internal static string MESSAGESSSENDEMAIL2 {
            get {
                return ResourceManager.GetString("MESSAGESSSENDEMAIL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu mensaje ha sido enviado. Pronto nos comunicaremos contigo..
        /// </summary>
        internal static string MESSAGESUCCESFULL {
            get {
                return ResourceManager.GetString("MESSAGESUCCESFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más info.
        /// </summary>
        internal static string MOREINFO {
            get {
                return ResourceManager.GetString("MOREINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más de.
        /// </summary>
        internal static string MOREOF {
            get {
                return ResourceManager.GetString("MOREOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más comentadas.
        /// </summary>
        internal static string MOSTCOMM {
            get {
                return ResourceManager.GetString("MOSTCOMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Actividad.
        /// </summary>
        internal static string MYACTIVITY {
            get {
                return ResourceManager.GetString("MYACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Ideas.
        /// </summary>
        internal static string MYIDEAS {
            get {
                return ResourceManager.GetString("MYIDEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre y Apellidos:.
        /// </summary>
        internal static string NAMEANDLAST {
            get {
                return ResourceManager.GetString("NAMEANDLAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los ciudadanos más cercanos.
        /// </summary>
        internal static string NEAREST {
            get {
                return ResourceManager.GetString("NEAREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron resultados para el parámetro de búsqueda.
        /// </summary>
        internal static string NORESULTPARAMETRO {
            get {
                return ResourceManager.GetString("NORESULTPARAMETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros.
        /// </summary>
        internal static string NO_RECORDS_FOUND {
            get {
                return ResourceManager.GetString("NO_RECORDS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudadanos participando.
        /// </summary>
        internal static string PARTICIPATING {
            get {
                return ResourceManager.GetString("PARTICIPATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIADOS.
        /// </summary>
        internal static string PARTNERS {
            get {
                return ResourceManager.GetString("PARTNERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubica tu respuesta en el mapa.
        /// </summary>
        internal static string PLACEMAP {
            get {
                return ResourceManager.GetString("PLACEMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingresa los caracteres que ves en la imagen:.
        /// </summary>
        internal static string PLEASEIT {
            get {
                return ResourceManager.GetString("PLEASEIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postula tu Reto.
        /// </summary>
        internal static string POSTULATES {
            get {
                return ResourceManager.GetString("POSTULATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postula tu Caso de Éxito.
        /// </summary>
        internal static string POSTULATESTUDY {
            get {
                return ResourceManager.GetString("POSTULATESTUDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                        &lt;strong&gt;PROTECCIÓN  DE DATOS Y POLÍTICA DE PRIVACIDAD DATOS PERSONALES&lt;/strong&gt;
        ///                    &lt;/p&gt;
        ///                    &lt;p&gt;
        ///                        Para la participación en la plataforma, &lt;strong&gt;RUTA N&lt;/strong&gt;, actuando como responsable de los datos, recopila información personal, como: Nombre, Apellido, email, usuario y contraseña.
        ///                    &lt;/p&gt;
        ///                    &lt;p&gt;
        ///                        &lt;strong&gt;RUTA N&lt;/strong&gt; recopila y utiliza la información pe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PRIVACYALL {
            get {
                return ResourceManager.GetString("PRIVACYALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Política de privacidad.
        /// </summary>
        internal static string PRIVACYPO {
            get {
                return ResourceManager.GetString("PRIVACYPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto de perfil:.
        /// </summary>
        internal static string PROFILEPI {
            get {
                return ResourceManager.GetString("PROFILEPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPUESTAS DE SOLUCIÓN.
        /// </summary>
        internal static string PROPOSEDSOLUTION {
            get {
                return ResourceManager.GetString("PROPOSEDSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar imagen.
        /// </summary>
        internal static string REMOVEPIC {
            get {
                return ResourceManager.GetString("REMOVEPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentímos. El recurso que buscas ya no esta disponible.
        /// </summary>
        internal static string RESOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar configuración.
        /// </summary>
        internal static string SAVESETTINGS {
            get {
                return ResourceManager.GetString("SAVESETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Buscas algo específico?.
        /// </summary>
        internal static string SEARCHESPECIFI {
            get {
                return ResourceManager.GetString("SEARCHESPECIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de la busqueda.
        /// </summary>
        internal static string SEARCH_RESULT {
            get {
                return ResourceManager.GetString("SEARCH_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver más.
        /// </summary>
        internal static string SEEMORE {
            get {
                return ResourceManager.GetString("SEEMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un motivo.
        /// </summary>
        internal static string SELECTREASON {
            get {
                return ResourceManager.GetString("SELECTREASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviarme un correo cuando un pulso está a.
        /// </summary>
        internal static string SENDAN {
            get {
                return ResourceManager.GetString("SENDAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIO DE CORREO.
        /// </summary>
        internal static string SENDINGMAIL {
            get {
                return ResourceManager.GetString("SENDINGMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviarme un correo cuando un pulso finalice.
        /// </summary>
        internal static string SENDME {
            get {
                return ResourceManager.GetString("SENDME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviarme un correo cuando se publique un nuevo pulso.
        /// </summary>
        internal static string SENDNEW {
            get {
                return ResourceManager.GetString("SENDNEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPARTIRLAS.
        /// </summary>
        internal static string SHAREITHERE {
            get {
                return ResourceManager.GetString("SHAREITHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miremos al mundo con ojos &quot;Co-Creadores&quot;, creyendo en la coopetición en vez de la competición!.
        /// </summary>
        internal static string SHAREVOTE {
            get {
                return ResourceManager.GetString("SHAREVOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o a través de las redes sociales.
        /// </summary>
        internal static string SOCIAL {
            get {
                return ResourceManager.GetString("SOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redes Sociales.
        /// </summary>
        internal static string SOCIALMEDIA {
            get {
                return ResourceManager.GetString("SOCIALMEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las acciones hablan más fuerte que los sueños..
        /// </summary>
        internal static string SPEAK {
            get {
                return ResourceManager.GetString("SPEAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empieza a escribir.
        /// </summary>
        internal static string START_TYPING {
            get {
                return ResourceManager.GetString("START_TYPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa un asunto.
        /// </summary>
        internal static string SUBJECT {
            get {
                return ResourceManager.GetString("SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido a Cities for Life!‏.
        /// </summary>
        internal static string SUBJECTWELCOME {
            get {
                return ResourceManager.GetString("SUBJECTWELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casos de exito.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustenta tu idea, sube un video.
        /// </summary>
        internal static string SUPPORT {
            get {
                return ResourceManager.GetString("SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apoya tu idea, sube una foto.
        /// </summary>
        internal static string SUPPORTPHOTO {
            get {
                return ResourceManager.GetString("SUPPORTPHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema esta ocupado. Intenta Nuevamente.
        /// </summary>
        internal static string SYSTEM_ERROR {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡CUÉNTANOS TUS IDEAS INNOVADORAS Y CONSTRUYE LA CIUDAD QUE SUEÑAS!.
        /// </summary>
        internal static string TELLCITY {
            get {
                return ResourceManager.GetString("TELLCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuéntanos tu opinión.
        /// </summary>
        internal static string TELLOPINION {
            get {
                return ResourceManager.GetString("TELLOPINION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                        &lt;strong&gt;TÉRMINOS DE USO PLATAFORMA CITIES FOR LIFE&lt;/strong&gt;
        ///                    &lt;/p&gt;
        ///                    &lt;p&gt;
        ///                        Lea atentamente los siguientes términos de uso (las “condiciones de uso” o “acuerdo”) antes de empezar a usar los servicios ofrecidos en “la plataforma de cocreación CITIES FOR LIFE”.
        ///                    &lt;/p&gt;
        ///                    &lt;p&gt;
        ///                        &lt;strong&gt;Resumen de la plataforma de cocreación CITIES FOR LIFE&lt;/strong&gt;
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TERANDCON {
            get {
                return ResourceManager.GetString("TERANDCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                            &lt;strong&gt;TÉRMINOS DE USO PLATAFORMA CITIES FOR LIFE&lt;/strong&gt;
        ///                        &lt;/p&gt;
        ///                        &lt;p&gt;
        ///                            Lea atentamente los siguientes términos de uso (las “condiciones de uso” o “acuerdo”) antes de empezar a usar los servicios ofrecidos en “la plataforma de cocreación CITIES FOR LIFE”.
        ///                        &lt;/p&gt;
        ///                        &lt;p&gt;
        ///                            &lt;strong&gt;Resumen de la plataforma de cocreación CITIES FOR L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TERMINS1 {
            get {
                return ResourceManager.GetString("TERMINS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                            &lt;strong&gt;1. Términos del acuerdo&lt;/strong&gt;
        ///                        &lt;/p&gt;
        ///                        &lt;p&gt;
        ///                            Los términos de este acuerdo regulan la relación entre el &lt;strong&gt;USUARIO&lt;/strong&gt; y &lt;strong&gt;RUTA N&lt;/strong&gt;, (en adelante &quot;EL ADMINISTRADOR&quot; con respecto al uso de la plataforma y sus servicios relacionados (el &quot;Servicio&quot;).
        ///                        &lt;/p&gt;
        ///                        &lt;p&gt;
        ///                            &lt;strong&gt;EL ADMINISTRADOR&lt;/strong&gt; es  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TERMINS2 {
            get {
                return ResourceManager.GetString("TERMINS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Transforma tu ciudad y&lt;/span&gt;&lt;br&gt;Haz que tu voz tenga eco en cualquier parte del mundo..
        /// </summary>
        internal static string TRANSCITY {
            get {
                return ResourceManager.GetString("TRANSCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Únete a la transformación de nuestra ciudad.
        /// </summary>
        internal static string TRANSFOR {
            get {
                return ResourceManager.GetString("TRANSFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aún no has participado en las ideas de otros ciudadanos. Empieza a participar en la cocreación de tu ciudad..
        /// </summary>
        internal static string TXTAUNNOHAS {
            get {
                return ResourceManager.GetString("TXTAUNNOHAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        internal static string TXTCHAPASS {
            get {
                return ResourceManager.GetString("TXTCHAPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa toda la información y gana 120 puntos.
        /// </summary>
        internal static string TXTCOMALL {
            get {
                return ResourceManager.GetString("TXTCOMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        internal static string TXTCONFPASS {
            get {
                return ResourceManager.GetString("TXTCONFPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        internal static string TXTDIDFOR {
            get {
                return ResourceManager.GetString("TXTDIDFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta información es privada, ningún otro ciudadano tiene acceso a ella.
        /// </summary>
        internal static string TXTINFORPRIVA {
            get {
                return ResourceManager.GetString("TXTINFORPRIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string TXTNEWPASS {
            get {
                return ResourceManager.GetString("TXTNEWPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CON.
        /// </summary>
        internal static string TXTOCON {
            get {
                return ResourceManager.GetString("TXTOCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información personal.
        /// </summary>
        internal static string TXTPERSINFOR {
            get {
                return ResourceManager.GetString("TXTPERSINFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar contraseña.
        /// </summary>
        internal static string TXTREMPASS {
            get {
                return ResourceManager.GetString("TXTREMPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione su idioma de preferencia.
        /// </summary>
        internal static string TXTSELECTLANGAGE {
            get {
                return ResourceManager.GetString("TXTSELECTLANGAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y condiciones.
        /// </summary>
        internal static string TXTTERMCOND {
            get {
                return ResourceManager.GetString("TXTTERMCOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de banner.
        /// </summary>
        internal static string TYPE_OF_BANNER {
            get {
                return ResourceManager.GetString("TYPE_OF_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear idea.
        /// </summary>
        internal static string UNBLOCK_IDEA {
            get {
                return ResourceManager.GetString("UNBLOCK_IDEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear usuario.
        /// </summary>
        internal static string UNBLOCK_USER {
            get {
                return ResourceManager.GetString("UNBLOCK_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dar de baja.
        /// </summary>
        internal static string UNSU {
            get {
                return ResourceManager.GetString("UNSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darme de baja.
        /// </summary>
        internal static string UNSUBSCRIBE {
            get {
                return ResourceManager.GetString("UNSUBSCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos cargados.
        /// </summary>
        internal static string UPLOADED_FILES {
            get {
                return ResourceManager.GetString("UPLOADED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sube una imagen.
        /// </summary>
        internal static string UPLOADPHOTO {
            get {
                return ResourceManager.GetString("UPLOADPHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es incorrecta, Por favor verifica nuevamente..
        /// </summary>
        internal static string USER_BAD_PASSWORD {
            get {
                return ResourceManager.GetString("USER_BAD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no esta en el sistema.
        /// </summary>
        internal static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de querer borrar permanentemente el usuario en Cities for Life?.
        /// </summary>
        internal static string VALIDACIONDELETEUSER {
            get {
                return ResourceManager.GetString("VALIDACIONDELETEUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuerda que esta es tu casa y puedes regresar cuando quieras..
        /// </summary>
        internal static string VALIDACIONDELETEUSER2 {
            get {
                return ResourceManager.GetString("VALIDACIONDELETEUSER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Por que lo das de baja?.
        /// </summary>
        internal static string VALIDACIONDELETEUSER2ADMIN {
            get {
                return ResourceManager.GetString("VALIDACIONDELETEUSER2ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Borrar la información?.
        /// </summary>
        internal static string VALIDACIONDELETEUSERHEADER {
            get {
                return ResourceManager.GetString("VALIDACIONDELETEUSERHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro?.
        /// </summary>
        internal static string VALIDACIONDELETEUSERHEADER2 {
            get {
                return ResourceManager.GetString("VALIDACIONDELETEUSERHEADER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar una ciudad.
        /// </summary>
        internal static string VALIDATIONCITY {
            get {
                return ResourceManager.GetString("VALIDATIONCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar el correo electrónico.
        /// </summary>
        internal static string VALIDATIONCORREO {
            get {
                return ResourceManager.GetString("VALIDATIONCORREO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar un formato válido de correo.
        /// </summary>
        internal static string VALIDATIONCORREOINVALIDO {
            get {
                return ResourceManager.GetString("VALIDATIONCORREOINVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar un país.
        /// </summary>
        internal static string VALIDATIONCOUNTRY {
            get {
                return ResourceManager.GetString("VALIDATIONCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar un idioma.
        /// </summary>
        internal static string VALIDATIONIDIOMA {
            get {
                return ResourceManager.GetString("VALIDATIONIDIOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar una ubicación.
        /// </summary>
        internal static string VALIDATIONLOCATION {
            get {
                return ResourceManager.GetString("VALIDATIONLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar un mensaje.
        /// </summary>
        internal static string VALIDATIONMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATIONMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar el nombre.
        /// </summary>
        internal static string VALIDATIONNAME {
            get {
                return ResourceManager.GetString("VALIDATIONNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar una contraseña.
        /// </summary>
        internal static string VALIDATIONPASSWORD {
            get {
                return ResourceManager.GetString("VALIDATIONPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes confirmar tu contraseña.
        /// </summary>
        internal static string VALIDATIONPASSWORDCONFIR {
            get {
                return ResourceManager.GetString("VALIDATIONPASSWORDCONFIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        internal static string VALIDATIONPASSWORDMASH {
            get {
                return ResourceManager.GetString("VALIDATIONPASSWORDMASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes aceptar las politicas de privacidad.
        /// </summary>
        internal static string VALIDATIONPOLICIES {
            get {
                return ResourceManager.GetString("VALIDATIONPOLICIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar un asunto.
        /// </summary>
        internal static string VALIDATIONSUBJECT {
            get {
                return ResourceManager.GetString("VALIDATIONSUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes aceptar los términos y condiciones.
        /// </summary>
        internal static string VALIDATIONTERMSCONDITIONS {
            get {
                return ResourceManager.GetString("VALIDATIONTERMSCONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        internal static string ValIDATIONTEST {
            get {
                return ResourceManager.GetString("ValIDATIONTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar una secci&amp;oacute;n para crear el contenido..
        /// </summary>
        internal static string VALID_SECTION_CONTENT {
            get {
                return ResourceManager.GetString("VALID_SECTION_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Muy bien!.
        /// </summary>
        internal static string VERYGOOD {
            get {
                return ResourceManager.GetString("VERYGOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video youtube.
        /// </summary>
        internal static string VIYOU {
            get {
                return ResourceManager.GetString("VIYOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya somos.
        /// </summary>
        internal static string WEALREADY {
            get {
                return ResourceManager.GetString("WEALREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha habido un momento más emocionante para ser parte de la comunidad global CITIES FOR LIFE que éste. Luego del lanzamiento durante el 1er Encuentro Global Cities for Life en Medellin, en septiembre 2015, nuestro alcance internacional e impacto continúan creciendo..
        /// </summary>
        internal static string WELCOMCI {
            get {
                return ResourceManager.GetString("WELCOMCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuéntanos, qué tienes en mente.
        /// </summary>
        internal static string WHATMIND {
            get {
                return ResourceManager.GetString("WHATMIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cúal de estas ideas te gusta más?.
        /// </summary>
        internal static string WHICHDO {
            get {
                return ResourceManager.GetString("WHICHDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Por qué reportas este contenido?.
        /// </summary>
        internal static string WHYCONTENT {
            get {
                return ResourceManager.GetString("WHYCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to escribe tu comentario aquí.
        /// </summary>
        internal static string WRITECOMMENT {
            get {
                return ResourceManager.GetString("WRITECOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe una introducción.
        /// </summary>
        internal static string WRITEINTRO {
            get {
                return ResourceManager.GetString("WRITEINTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escríbelo aquí.
        /// </summary>
        internal static string WRITEITHERE {
            get {
                return ResourceManager.GetString("WRITEITHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe aquí el título.
        /// </summary>
        internal static string WRITETITLE {
            get {
                return ResourceManager.GetString("WRITETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe tu número celular.
        /// </summary>
        internal static string WRITEYOU {
            get {
                return ResourceManager.GetString("WRITEYOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes subir una imagen o un video de Youtube.
        /// </summary>
        internal static string YOUCANGO {
            get {
                return ResourceManager.GetString("YOUCANGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si tiene alguna pregunta, por favor escríbanos a.
        /// </summary>
        internal static string YOUHAVEQUESTION {
            get {
                return ResourceManager.GetString("YOUHAVEQUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu idea podría llevarse a cabo.
        /// </summary>
        internal static string YOURCOULD {
            get {
                return ResourceManager.GetString("YOURCOULD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted se encuentra en.
        /// </summary>
        internal static string YOU_ARE_IN {
            get {
                return ResourceManager.GetString("YOU_ARE_IN", resourceCulture);
            }
        }
    }
}
