//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string ACCEPT {
            get {
                return ResourceManager.GetString("ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad.
        /// </summary>
        internal static string ACTIVITY {
            get {
                return ResourceManager.GetString("ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información adicional.
        /// </summary>
        internal static string ADDITIONAL_INFORMATION {
            get {
                return ResourceManager.GetString("ADDITIONAL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        internal static string ADMINISTRATION {
            get {
                return ResourceManager.GetString("ADMINISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad.
        /// </summary>
        internal static string AGE {
            get {
                return ResourceManager.GetString("AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hace.
        /// </summary>
        internal static string AGO {
            get {
                return ResourceManager.GetString("AGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        internal static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliados.
        /// </summary>
        internal static string ALLIES {
            get {
                return ResourceManager.GetString("ALLIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string ALLS {
            get {
                return ResourceManager.GetString("ALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuestas.
        /// </summary>
        internal static string ANSWERS {
            get {
                return ResourceManager.GetString("ANSWERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninguna.
        /// </summary>
        internal static string ANY {
            get {
                return ResourceManager.GetString("ANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen de fondo.
        /// </summary>
        internal static string BACKCROUNDIMAGE {
            get {
                return ResourceManager.GetString("BACKCROUNDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impactos que ha tenido.
        /// </summary>
        internal static string BEENIMPACT {
            get {
                return ResourceManager.GetString("BEENIMPACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string BLOG {
            get {
                return ResourceManager.GetString("BLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuerpo:.
        /// </summary>
        internal static string BODY {
            get {
                return ResourceManager.GetString("BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        internal static string BUDGET {
            get {
                return ResourceManager.GetString("BUDGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        internal static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reto.
        /// </summary>
        internal static string CHALL {
            get {
                return ResourceManager.GetString("CHALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retos.
        /// </summary>
        internal static string CHALLENGES {
            get {
                return ResourceManager.GetString("CHALLENGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué retos se han afrontado?.
        /// </summary>
        internal static string CHALLENGESFACED {
            get {
                return ResourceManager.GetString("CHALLENGESFACED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteres.
        /// </summary>
        internal static string CHARACTERS {
            get {
                return ResourceManager.GetString("CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisado.
        /// </summary>
        internal static string CHECKED {
            get {
                return ResourceManager.GetString("CHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudadanos.
        /// </summary>
        internal static string CITIZENS {
            get {
                return ResourceManager.GetString("CITIZENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        internal static string CLEAN {
            get {
                return ResourceManager.GetString("CLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clonar contenido.
        /// </summary>
        internal static string CLONE_CONTENT {
            get {
                return ResourceManager.GetString("CLONE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        internal static string CLOSE_SESSION {
            get {
                return ResourceManager.GetString("CLOSE_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentar.
        /// </summary>
        internal static string COMMENT {
            get {
                return ResourceManager.GetString("COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        internal static string COMMENTS {
            get {
                return ResourceManager.GetString("COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        internal static string COMMENTSSINGULAR {
            get {
                return ResourceManager.GetString("COMMENTSSINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cuáles son los problemas concretos que han tratado o han resuelto?.
        /// </summary>
        internal static string CONCRETE_PROBLEMS {
            get {
                return ResourceManager.GetString("CONCRETE_PROBLEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactar.
        /// </summary>
        internal static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctanos.
        /// </summary>
        internal static string CONTACTUS {
            get {
                return ResourceManager.GetString("CONTACTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido en Español.
        /// </summary>
        internal static string CONTENT {
            get {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido en Inglés.
        /// </summary>
        internal static string CONTENT2 {
            get {
                return ResourceManager.GetString("CONTENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenidos.
        /// </summary>
        internal static string CONTENTS {
            get {
                return ResourceManager.GetString("CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenidos disponibles.
        /// </summary>
        internal static string CONTENT_AVAILABLE {
            get {
                return ResourceManager.GetString("CONTENT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlador.
        /// </summary>
        internal static string CONTROLLER {
            get {
                return ResourceManager.GetString("CONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de creación.
        /// </summary>
        internal static string CREATION_DATE {
            get {
                return ResourceManager.GetString("CREATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creativo.
        /// </summary>
        internal static string CREATIVE {
            get {
                return ResourceManager.GetString("CREATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivado.
        /// </summary>
        internal static string DEACTIVATE {
            get {
                return ResourceManager.GetString("DEACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Entrega.
        /// </summary>
        internal static string DELIVERYDATE {
            get {
                return ResourceManager.GetString("DELIVERYDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descríbelo:.
        /// </summary>
        internal static string DESCRIBE {
            get {
                return ResourceManager.GetString("DESCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gana.
        /// </summary>
        internal static string DESIRE {
            get {
                return ResourceManager.GetString("DESIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string DETAIL {
            get {
                return ResourceManager.GetString("DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos, Fotos, Noticias, Otros documentos.
        /// </summary>
        internal static string DOCUMENTS {
            get {
                return ResourceManager.GetString("DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor inserte algunos enlaces que tengan información descriptiva del proyecto.
        /// </summary>
        internal static string DOCUMENTS_HELP {
            get {
                return ResourceManager.GetString("DOCUMENTS_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correo@correo.co.
        /// </summary>
        internal static string EMAIL_EXAMPLE {
            get {
                return ResourceManager.GetString("EMAIL_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha final.
        /// </summary>
        internal static string END_DATE {
            get {
                return ResourceManager.GetString("END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades responsables.
        /// </summary>
        internal static string ENTITIESRESPONSIBLE {
            get {
                return ResourceManager.GetString("ENTITIESRESPONSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        internal static string ERASE {
            get {
                return ResourceManager.GetString("ERASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplo.
        /// </summary>
        internal static string EXAMPLE {
            get {
                return ResourceManager.GetString("EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        internal static string EXPORT {
            get {
                return ResourceManager.GetString("EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destacado.
        /// </summary>
        internal static string FEATURED {
            get {
                return ResourceManager.GetString("FEATURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos.
        /// </summary>
        internal static string FILES {
            get {
                return ResourceManager.GetString("FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string FIND {
            get {
                return ResourceManager.GetString("FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados de búsqueda.
        /// </summary>
        internal static string FINDREULTS {
            get {
                return ResourceManager.GetString("FINDREULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero.
        /// </summary>
        internal static string FIRST {
            get {
                return ResourceManager.GetString("FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpetas.
        /// </summary>
        internal static string FOLDERS {
            get {
                return ResourceManager.GetString("FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string FOLLOWING {
            get {
                return ResourceManager.GetString("FOLLOWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lidera.
        /// </summary>
        internal static string FOOTERLEAD {
            get {
                return ResourceManager.GetString("FOOTERLEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliados.
        /// </summary>
        internal static string FOOTERSPONSOR {
            get {
                return ResourceManager.GetString("FOOTERSPONSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url amigable.
        /// </summary>
        internal static string FRIENDLY_URL {
            get {
                return ResourceManager.GetString("FRIENDLY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        internal static string FROM {
            get {
                return ResourceManager.GetString("FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genero.
        /// </summary>
        internal static string GENDER {
            get {
                return ResourceManager.GetString("GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !CONÓCENOS!.
        /// </summary>
        internal static string GETINSPIRED {
            get {
                return ResourceManager.GetString("GETINSPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !CONÓCENOS!.
        /// </summary>
        internal static string GETINSPIRED2 {
            get {
                return ResourceManager.GetString("GETINSPIRED2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odio.
        /// </summary>
        internal static string HATE {
            get {
                return ResourceManager.GetString("HATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latidos.
        /// </summary>
        internal static string HEARTBEAT {
            get {
                return ResourceManager.GetString("HEARTBEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto.
        /// </summary>
        internal static string HEIGHT {
            get {
                return ResourceManager.GetString("HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea.
        /// </summary>
        internal static string IDEA {
            get {
                return ResourceManager.GetString("IDEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideador.
        /// </summary>
        internal static string IDEAGENERATOR {
            get {
                return ResourceManager.GetString("IDEAGENERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imágen.
        /// </summary>
        internal static string IMAGE {
            get {
                return ResourceManager.GetString("IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string INACTIVE {
            get {
                return ResourceManager.GetString("INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Por qué considera el proyecto como una solución urbana innovadora?.
        /// </summary>
        internal static string INNOVATIVE_URBAN_SOLUTION {
            get {
                return ResourceManager.GetString("INNOVATIVE_URBAN_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor describa el impacto social, la replicabilidad y reputación (premios), etc. del caso.
        /// </summary>
        internal static string INNOVATIVE_URBAN_SOLUTION_HELP {
            get {
                return ResourceManager.GetString("INNOVATIVE_URBAN_SOLUTION_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intereses.
        /// </summary>
        internal static string INTERESTS {
            get {
                return ResourceManager.GetString("INTERESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducción en Español.
        /// </summary>
        internal static string INTRODUCTION {
            get {
                return ResourceManager.GetString("INTRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducción en Inglés.
        /// </summary>
        internal static string INTRODUCTION2 {
            get {
                return ResourceManager.GetString("INTRODUCTION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesión.
        /// </summary>
        internal static string JOB_TITLE {
            get {
                return ResourceManager.GetString("JOB_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerente.
        /// </summary>
        internal static string JOB_TITLE_EXAMPLE {
            get {
                return ResourceManager.GetString("JOB_TITLE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SÚMATE AL ECOSISTEMA.
        /// </summary>
        internal static string JOINUS {
            get {
                return ResourceManager.GetString("JOINUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palabras Claves.
        /// </summary>
        internal static string KEYWORDS {
            get {
                return ResourceManager.GetString("KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor dénos algunas palabras claves que describan su caso.
        /// </summary>
        internal static string KEYWORDS_HELP {
            get {
                return ResourceManager.GetString("KEYWORDS_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma:.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenguage predeterminado.
        /// </summary>
        internal static string LANGUAGE_DEFAULT {
            get {
                return ResourceManager.GetString("LANGUAGE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último.
        /// </summary>
        internal static string LAST {
            get {
                return ResourceManager.GetString("LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendario.
        /// </summary>
        internal static string LEGENDARY {
            get {
                return ResourceManager.GetString("LEGENDARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado.
        /// </summary>
        internal static string LIST {
            get {
                return ResourceManager.GetString("LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        internal static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando.
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        internal static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hombre.
        /// </summary>
        internal static string MAN {
            get {
                return ResourceManager.GetString("MAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto:.
        /// </summary>
        internal static string MATTER {
            get {
                return ResourceManager.GetString("MATTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje:.
        /// </summary>
        internal static string MESSAGE {
            get {
                return ResourceManager.GetString("MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movil.
        /// </summary>
        internal static string MOBILE {
            get {
                return ResourceManager.GetString("MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string MODEL {
            get {
                return ResourceManager.GetString("MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de modificación.
        /// </summary>
        internal static string MODIFIED_DATE {
            get {
                return ResourceManager.GetString("MODIFIED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulos.
        /// </summary>
        internal static string MODULS {
            get {
                return ResourceManager.GetString("MODULS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        internal static string MOTIVE {
            get {
                return ResourceManager.GetString("MOTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to múltiple.
        /// </summary>
        internal static string MULTIPLE {
            get {
                return ResourceManager.GetString("MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre en Español.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre en Inglés.
        /// </summary>
        internal static string NAME2 {
            get {
                return ResourceManager.GetString("NAME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string NAMETAG {
            get {
                return ResourceManager.GetString("NAMETAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redes.
        /// </summary>
        internal static string NETWORKS {
            get {
                return ResourceManager.GetString("NETWORKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTICIAS.
        /// </summary>
        internal static string NEWS {
            get {
                return ResourceManager.GetString("NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abierta.
        /// </summary>
        internal static string OPENQUESTION {
            get {
                return ResourceManager.GetString("OPENQUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        internal static string ORDER {
            get {
                return ResourceManager.GetString("ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización.
        /// </summary>
        internal static string ORGANIZATION {
            get {
                return ResourceManager.GetString("ORGANIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        internal static string OTHER {
            get {
                return ResourceManager.GetString("OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTICIPA.
        /// </summary>
        internal static string PARTICIPATES {
            get {
                return ResourceManager.GetString("PARTICIPATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        internal static string PENDING {
            get {
                return ResourceManager.GetString("PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        internal static string PEOPLE {
            get {
                return ResourceManager.GetString("PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos.
        /// </summary>
        internal static string PERMISSIONS {
            get {
                return ResourceManager.GetString("PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué contenido deseas encontrar?.
        /// </summary>
        internal static string PLACEHOLDERFIND {
            get {
                return ResourceManager.GetString("PLACEHOLDERFIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populares.
        /// </summary>
        internal static string POPULAR {
            get {
                return ResourceManager.GetString("POPULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pornografia.
        /// </summary>
        internal static string PORGRAPHY {
            get {
                return ResourceManager.GetString("PORGRAPHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición.
        /// </summary>
        internal static string POSITION {
            get {
                return ResourceManager.GetString("POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postular tu Caso de Éxito.
        /// </summary>
        internal static string POSTULATES_SUCCESS_STORY {
            get {
                return ResourceManager.GetString("POSTULATES_SUCCESS_STORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postular Caso de Éxito.
        /// </summary>
        internal static string POSTULATING_SUCCESS_STORY {
            get {
                return ResourceManager.GetString("POSTULATING_SUCCESS_STORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Postulaciones.
        /// </summary>
        internal static string POSTULATIONSLIST {
            get {
                return ResourceManager.GetString("POSTULATIONSLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefijo.
        /// </summary>
        internal static string PREFIX {
            get {
                return ResourceManager.GetString("PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        internal static string PREVIOUS {
            get {
                return ResourceManager.GetString("PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premio en Español.
        /// </summary>
        internal static string PRIZE {
            get {
                return ResourceManager.GetString("PRIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premio en Inglés.
        /// </summary>
        internal static string PRIZE2 {
            get {
                return ResourceManager.GetString("PRIZE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proactivo.
        /// </summary>
        internal static string PROACTIVE {
            get {
                return ResourceManager.GetString("PROACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cuáles son los problemas concretos que han tratado o han resuelto? (en Español).
        /// </summary>
        internal static string PROBLEMSSOLVED {
            get {
                return ResourceManager.GetString("PROBLEMSSOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cuáles son los problemas concretos que han tratado o han resuelto? (en Inglés).
        /// </summary>
        internal static string PROBLEMSSOLVED2 {
            get {
                return ResourceManager.GetString("PROBLEMSSOLVED2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesión.
        /// </summary>
        internal static string PROFESSION {
            get {
                return ResourceManager.GetString("PROFESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string PROFILES {
            get {
                return ResourceManager.GetString("PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona de contacto.
        /// </summary>
        internal static string PROJECTLEADERS {
            get {
                return ResourceManager.GetString("PROJECTLEADERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del Proyecto.
        /// </summary>
        internal static string PROJECT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PROJECT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuales son las metas y las características más relevantes de su proyecto.
        /// </summary>
        internal static string PROJECT_DESCRIPTION_HELP {
            get {
                return ResourceManager.GetString("PROJECT_DESCRIPTION_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Proyecto.
        /// </summary>
        internal static string PROJECT_NAME {
            get {
                return ResourceManager.GetString("PROJECT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejoramiento de movilidad en Medellín por medio de las bicicletas.
        /// </summary>
        internal static string PROJECT_NAME_HELP {
            get {
                return ResourceManager.GetString("PROJECT_NAME_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable del Proyecto.
        /// </summary>
        internal static string PROJECT_RESPONSIBLE {
            get {
                return ResourceManager.GetString("PROJECT_RESPONSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROYECTOS.
        /// </summary>
        internal static string PROYECTS {
            get {
                return ResourceManager.GetString("PROYECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de publicación.
        /// </summary>
        internal static string PUBLISHDATE {
            get {
                return ResourceManager.GetString("PUBLISHDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicado.
        /// </summary>
        internal static string PUBLISHED {
            get {
                return ResourceManager.GetString("PUBLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLICAR CASO.
        /// </summary>
        internal static string PUBLISH_SUCCESS_STORY {
            get {
                return ResourceManager.GetString("PUBLISH_SUCCESS_STORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string QUALITY {
            get {
                return ResourceManager.GetString("QUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREGUNTA.
        /// </summary>
        internal static string QUESTION {
            get {
                return ResourceManager.GetString("QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aleatorios.
        /// </summary>
        internal static string RANDOM {
            get {
                return ResourceManager.GetString("RANDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leer más.
        /// </summary>
        internal static string READMORE {
            get {
                return ResourceManager.GetString("READMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recientes.
        /// </summary>
        internal static string RECENT {
            get {
                return ResourceManager.GetString("RECENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomendar.
        /// </summary>
        internal static string RECOMMEND {
            get {
                return ResourceManager.GetString("RECOMMEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomendado.
        /// </summary>
        internal static string RECOMMENDED {
            get {
                return ResourceManager.GetString("RECOMMENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazado.
        /// </summary>
        internal static string REJECTED {
            get {
                return ResourceManager.GetString("REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECHAZAR CASO.
        /// </summary>
        internal static string REJECT_SUCCESS_STORY {
            get {
                return ResourceManager.GetString("REJECT_SUCCESS_STORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlaces relacionados.
        /// </summary>
        internal static string RELATEDLINKS {
            get {
                return ResourceManager.GetString("RELATEDLINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urls Relacionadas&lt;br /&gt;Se debe ingresar una url por fila, maximo 250 caracteres&lt;br /&gt;.
        /// </summary>
        internal static string RELATEDURLS {
            get {
                return ResourceManager.GetString("RELATEDURLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenidos relacionados.
        /// </summary>
        internal static string RELATED_CONTENT {
            get {
                return ResourceManager.GetString("RELATED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportar.
        /// </summary>
        internal static string REPORT {
            get {
                return ResourceManager.GetString("REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Requerido.
        /// </summary>
        internal static string REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar tamaño.
        /// </summary>
        internal static string RESIZE {
            get {
                return ResourceManager.GetString("RESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades Responsables.
        /// </summary>
        internal static string RESPONSIBLE_ENTITIES {
            get {
                return ResourceManager.GetString("RESPONSIBLE_ENTITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qué instituciones públicas o privadas, organizaciones no gubernamentales u otras instituciones que hayan planeado y ejecutado el proyecto.
        /// </summary>
        internal static string RESPONSIBLE_ENTITIES_HELP {
            get {
                return ResourceManager.GetString("RESPONSIBLE_ENTITIES_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolucionario.
        /// </summary>
        internal static string REVOLUTIONARY {
            get {
                return ResourceManager.GetString("REVOLUTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiz.
        /// </summary>
        internal static string ROOT {
            get {
                return ResourceManager.GetString("ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y salir.
        /// </summary>
        internal static string SAVE_EXIT {
            get {
                return ResourceManager.GetString("SAVE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos.
        /// </summary>
        internal static string SCORE {
            get {
                return ResourceManager.GetString("SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección.
        /// </summary>
        internal static string SECTION {
            get {
                return ResourceManager.GetString("SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secccion.
        /// </summary>
        internal static string SECTIONS {
            get {
                return ResourceManager.GetString("SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione.
        /// </summary>
        internal static string SELECT {
            get {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccion.
        /// </summary>
        internal static string SELECTION {
            get {
                return ResourceManager.GetString("SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string SELECTVERBO {
            get {
                return ResourceManager.GetString("SELECTVERBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una Categoría.
        /// </summary>
        internal static string SELECT_CATEGORY {
            get {
                return ResourceManager.GetString("SELECT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una Ciudad.
        /// </summary>
        internal static string SELECT_CITY {
            get {
                return ResourceManager.GetString("SELECT_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un País.
        /// </summary>
        internal static string SELECT_COUNTRY {
            get {
                return ResourceManager.GetString("SELECT_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartir.
        /// </summary>
        internal static string SHARE {
            get {
                return ResourceManager.GetString("SHARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño.
        /// </summary>
        internal static string SIZE {
            get {
                return ResourceManager.GetString("SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar.
        /// </summary>
        internal static string SORT {
            get {
                return ResourceManager.GetString("SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de inicio.
        /// </summary>
        internal static string START_DATE {
            get {
                return ResourceManager.GetString("START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Caso.
        /// </summary>
        internal static string STORYNAME {
            get {
                return ResourceManager.GetString("STORYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del Caso.
        /// </summary>
        internal static string STORYSTATUS {
            get {
                return ResourceManager.GetString("STORYSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casos de éxito.
        /// </summary>
        internal static string SUCCESSSTORY {
            get {
                return ResourceManager.GetString("SUCCESSSTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Por qué considera el proyecto como una solución urbana innovadora? (en Español)&lt;br /&gt;Por favor describa el impacto social, la replicabilidad, la reputación (premios, reonocimientios), etc., del proyecto.&lt;br /&gt;.
        /// </summary>
        internal static string URBANSOLUTION {
            get {
                return ResourceManager.GetString("URBANSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Por qué considera el proyecto como una solución urbana innovadora? (en Inglés)&lt;br /&gt;Por favor describa el impacto social, la replicabilidad, la reputación (premios, reonocimientios), etc., del proyecto.&lt;br /&gt;.
        /// </summary>
        internal static string URBANSOLUTION2 {
            get {
                return ResourceManager.GetString("URBANSOLUTION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuarios.
        /// </summary>
        internal static string USERS {
            get {
                return ResourceManager.GetString("USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario.
        /// </summary>
        internal static string USER_NAME {
            get {
                return ResourceManager.GetString("USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string VIDEO {
            get {
                return ResourceManager.GetString("VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violencia.
        /// </summary>
        internal static string VIOLENCE {
            get {
                return ResourceManager.GetString("VIOLENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitar.
        /// </summary>
        internal static string VISI {
            get {
                return ResourceManager.GetString("VISI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISÍTANOS.
        /// </summary>
        internal static string VISIT {
            get {
                return ResourceManager.GetString("VISIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votar.
        /// </summary>
        internal static string VOTE {
            get {
                return ResourceManager.GetString("VOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho.
        /// </summary>
        internal static string WIDTH {
            get {
                return ResourceManager.GetString("WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mujer.
        /// </summary>
        internal static string WOMAN {
            get {
                return ResourceManager.GetString("WOMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unieron.
        /// </summary>
        internal static string YOINED {
            get {
                return ResourceManager.GetString("YOINED", resourceCulture);
            }
        }
    }
}
